### ISSUE TITLE
Linux 运行idGen的时候报错

### ISSUE THREAD

**Issue by majintao** [sumory/gru#2]
[12-30 22:44:29.781] [INFO] com.sumory.gru.idgen.main.IdGenMain.main(IdGenMain.java:34) - Use container type([spring]) to run dubbo serivce.
Exception in thread "main" java.lang.NoClassDefFoundError: com/netflix/curator/framework/api/CuratorWatcher
        at com.alibaba.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.connect(CuratorZookeeperTransporter.java:10)
        at com.alibaba.dubbo.remoting.zookeeper.ZookeeperTransporter$Adpative.connect(ZookeeperTransporter$Adpative.java)
        at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.<init>(ZookeeperRegistry.java:71)
        at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:37)
        at com.alibaba.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:94)
        at com.alibaba.dubbo.registry.RegistryFactory$Adpative.getRegistry(RegistryFactory$Adpative.java)
        at com.alibaba.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:190)
        at com.alibaba.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:109)
        at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:54)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:53)
        at com.alibaba.dubbo.rpc.Protocol$Adpative.export(Protocol$Adpative.java)
        at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:485)
        at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:281)
        at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:242)
        at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:143)
        at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:109)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:98)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:776)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:485)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
        at com.alibaba.dubbo.container.spring.SpringContainer.start(SpringContainer.java:50)
        at com.sumory.gru.idgen.main.IdGenMain.main(IdGenMain.java:57)
Caused by: java.lang.ClassNotFoundException: com.netflix.curator.framework.api.CuratorWatcher
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 24 more

**Comment by majintao** [comment]
Pom配置添加：
<dependency>
            <groupId>com.netflix.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>1.1.10</version>
</dependency>

解决了！
